server:
  port: 8880
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/disou_db?useUnicode=true&characterEncoding=utf8
    username: self
    password: xxxxxxx
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: xx.xx.xx.xx
    port: 6379
    timeout: 5000
    password: 1234
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
#knife4j:
#  enable: true
#  production: true